import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import { getFirestore, collection, addDoc, getDocs, query, where, orderBy, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyBE0V4h1u8G_-9KcG0KpuMNog6GhYsqSo0',authDomain:'atividadesvillani.firebaseapp.com',projectId:'atividadesvillani',storageBucket:'atividadesvillani.firebasestorage.app',messagingSenderId:'601054930865',appId:'1:601054930865:web:962a8a97a02178f75cbf90'};
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app);let uid=null;try{uid=(await signInAnonymously(auth)).user.uid}catch(e){console.warn('Ative o login anônimo no Firebase Authentication.',e)}

const Q={
'7':[ {q:'Lucas iniciou com R$ 150, gastou R$ 200, recebeu R$ 80 e depois gastou R$ 40 e R$ 50. Qual é o saldo final?',o:['R$ 60 positivo','R$ 10 negativo','R$ 60 negativo','R$ 110 negativo'],a:2},{q:'Júlia recebe R$ 400 e gasta R$ 270 por mês. Para um curso, pode pagar 4× R$155 ou 6× R$110. Qual opção cabe no orçamento mensal?',o:['Plano B: 6× R$110','Plano A: 4× R$155','Plano A, usando crédito para cobrir a diferença','Nenhuma opção'],a:0},{q:'Notebook custa R$ 2.000. No PIX há 10% de desconto; no cartão são 5× R$440. Qual interpretação está correta?',o:['O desconto PIX não reduz o custo','Parcelar é melhor só porque a parcela é menor','O parcelamento é sem juros','O parcelamento acrescenta R$ 200 ao preço inicial'],a:3},{q:'R$ 5.000 são simulados em: CDB (+250,50 e +250,50), multimercado (+400,25 e −150,75) e ações (+800,50 e −950). Qual termina com maior saldo?',o:['Ações','Fundo multimercado','CDB prefixado','Nenhum'],a:2}],
'8':[ {q:'Uma família recebe R$ 4.500, gasta R$ 4.850 e quer ainda poupar R$150. Sem reduzir despesas essenciais nem zerar supérfluas, qual ajuste funciona?',o:['−R$200 shopping e −R$150 delivery','−R$500 supermercado','Zerar streaming e −R$350 delivery','−R$250 delivery e −R$250 shopping'],a:3},{q:'Júlia tem R$2.400 de despesas essenciais e quer reserva equivalente a 3 meses. Guardando R$400/mês, quanto tempo levará?',o:['6 meses','12 meses','18 meses','24 meses'],a:2},{q:'Qual classificação está adequada?',o:['Aluguel: fixa e essencial; cinema: variável e supérflua; reserva: segurança financeira','Supermercado: fixa e supérflua; plano de saúde: variável e supérflua','Energia: fixa e supérflua; aluguel: variável e lazer','Reserva: supérflua; supermercado: moradia'],a:0},{q:'Renda de R$5.000: necessidades R$3.000, desejos R$1.500 e poupança R$500. Quais são os percentuais?',o:['50% / 30% / 20%','50% / 40% / 10%','60% / 20% / 20%','60% / 30% / 10%'],a:3}],
'9':[ {q:'No jogo, cada acerto vale +4 e uma penalidade vale −6. Lucas teve uma penalidade e terminou com 10 pontos. Quantos acertos?',o:['1','4','10','16'],a:1},{q:'3 cadernos iguais e uma caneta de R$5 totalizam R$26. Chamando o caderno de v, qual equação representa a situação?',o:['3v + 5 = 26','3(v + 5) = 26','v + 5 = 26','3v − 5 = 26'],a:0},{q:'Um canteiro quadrado tem lado x e área 81 m². Qual equação permite encontrar x?',o:['4x=81','2x=81','x²=81','x²+81=0'],a:2},{q:'Um número elevado ao quadrado resulta em 49. Quais valores satisfazem?',o:['Apenas 7','7 ou −7','24,5 ou −24,5','Apenas 49'],a:1},{q:'Um quadrado tem área 64 m² e lado (x+3)m. Qual é x?',o:['5','8','32','61'],a:0},{q:'36 cadeiras estão em fileiras iguais. Cada fileira tem 5 cadeiras a mais que a quantidade de fileiras. Quantas fileiras?',o:['4','6','9','31'],a:0},{q:'A diferença entre o quadrado de um número e seu quíntuplo é −6. Quais valores resolvem?',o:['2 e 3','−2 e −3','1 e 6','5 e 6'],a:0},{q:'Para x² + 2x + 5 = 0, o que o discriminante indica?',o:['Duas soluções reais diferentes','Uma solução real','Não há solução real','Infinitas soluções reais'],a:2},{q:'Um retângulo tem perímetro 14 m e área 12 m². Quais são seus lados?',o:['3 m e 4 m','2 m e 6 m','1 m e 12 m','2 m e 5 m'],a:0},{q:'A altura é h = −5t² + 20. Em que instante após o lançamento h=15 m?',o:['1 segundo','1 e 3 segundos','−1 e 3 segundos','0 e 4 segundos'],a:0}]
};
const $=s=>document.querySelector(s),shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};let state={};
$('#classroom').addEventListener('change',e=>loadRanking(e.target.value));$('#startForm').addEventListener('submit',e=>{e.preventDefault();let room=$('#classroom').value,name=$('#name').value.trim();if(!room||!name)return;let grade=room[0];state={name,room,grade,questions:shuffle(Q[grade]),i:0,score:0,answers:[]};$('#start').classList.add('hidden');$('#quiz').classList.remove('hidden');$('#who').textContent=`${name} • ${room}`;$('#subject').textContent=grade==='9'?'Matemática':'Educação Financeira';render()});
function render(){let q=state.questions[state.i];$('#qnum').textContent=`${state.i+1}/${state.questions.length}`;$('#scoreLive').textContent=`🔥 ${state.score} pts`;$('#bar').style.width=`${state.i/state.questions.length*100}%`;let opts=shuffle(q.o.map((t,i)=>({t,correct:i===q.a})));$('#questionCard').innerHTML=`<h3>${q.q}</h3><div id="opts"></div>`;opts.forEach(x=>{let b=document.createElement('button');b.className='option';b.textContent=x.t;b.onclick=()=>answer(b,x.correct,q);$('#opts').appendChild(b)})}
function answer(btn,correct,q){document.querySelectorAll('.option').forEach(b=>b.disabled=true);btn.classList.add(correct?'correct':'wrong');if(correct)state.score+=100;state.answers.push({question:q.q,correct});setTimeout(()=>{state.i++;state.i<state.questions.length?render():finish()},650)}
async function finish(){let total=state.questions.length*100,pct=Math.round(state.score/total*100);$('#quiz').classList.add('hidden');$('#result').classList.remove('hidden');$('#finalScore').textContent=state.score;$('#resultTitle').textContent=pct===100?'Gabaritou! 🚀':pct>=70?'Mandou muito bem! 🔥':pct>=50?'Boa! Continue evoluindo 💪':'Desafio concluído! 🎯';$('#resultText').textContent=`Você acertou ${state.score/100} de ${state.questions.length} questões (${pct}%).`;try{await addDoc(collection(db,'resultados'),{nome:state.name,turma:state.room,serie:Number(state.grade),disciplina:state.grade==='9'?'Matemática':'Educação Financeira',pontos:state.score,total,percentual:pct,acertos:state.score/100,questoes:state.questions.length,uid:uid||'sem-auth',createdAt:serverTimestamp()})}catch(e){console.error(e)}loadRanking(state.room)}
async function loadRanking(room){if(!room)return;$('#rankingLabel').textContent=`Turma ${room}`;$('#rankingList').innerHTML='<p class="muted">Carregando...</p>';try{let snap=await getDocs(query(collection(db,'resultados'),where('turma','==',room),orderBy('pontos','desc'),limit(10)));let rows=snap.docs.map(d=>d.data());$('#rankingList').innerHTML=rows.length?rows.map((r,i)=>`<div class="rankRow"><div class="left"><div class="pos">${i+1}</div><div><b>${escapeHtml(r.nome)}</b><div class="muted">${r.acertos}/${r.questoes} acertos</div></div></div><div class="pts">${r.pontos} pts</div></div>`).join(''):'<p class="muted">Ainda não há resultados nessa turma.</p>'}catch(e){console.error(e);$('#rankingList').innerHTML='<p class="muted">Não foi possível carregar o ranking. Confira o índice/regras do Firestore.</p>'}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function msg(){let pct=Math.round(state.score/(state.questions.length*100)*100);return `🏆 Desafio Villani\n${state.name} • ${state.room}\n${state.grade==='9'?'Matemática':'Educação Financeira'}\nResultado: ${state.score/100}/${state.questions.length} (${pct}%) • ${state.score} pontos`}
$('#shareTeacher').onclick=()=>window.open(`https://wa.me/5519996470380?text=${encodeURIComponent(msg())}`,'_blank');$('#shareFriend').onclick=async()=>{let text=msg()+'\nConsegue superar minha pontuação? 😎';if(navigator.share)try{await navigator.share({title:'Desafio Villani',text,url:location.href})}catch{}else window.open(`https://wa.me/?text=${encodeURIComponent(text+'\n'+location.href)}`,'_blank')};$('#again').onclick=()=>location.reload();$('#refresh').onclick=()=>loadRanking($('#classroom').value||state.room);
